from __future__ import annotations

import json
from pathlib import Path

from hijack.core.models import AnalysisRule, CategoryResult, SessionResult
from hijack.core.preprocessor import build_layer_stats

_LAYERS = ["frontend", "backend", "db", "devops", "shared"]

_LAYER_FILE_NAMES: dict[str, str] = {
    "frontend": "frontend.md",
    "backend": "backend.md",
    "db": "database.md",
    "devops": "devops.md",
    "shared": "shared.md",
}

_LAYER_CONTEXT: dict[str, str] = {
    "frontend": "프론트엔드 파일 작업 (.tsx/.jsx, frontend/) → 이 파일 + shared.md",
    "backend": "백엔드 파일 작업 (.py, backend/) → 이 파일 + shared.md",
    "db": "DB 파일 작업 (migrations/, models/) → 이 파일 + shared.md",
    "devops": "CI/인프라 작업 (.github/, Dockerfile) → 이 파일 + shared.md",
    "shared": "공통 규칙 (레이어 무관) → 모든 작업에 적용",
}


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------

def render_meta_md(result: SessionResult) -> str:
    lines = [
        "# Analysis Metadata",
        "",
        f"- **Session ID**: `{result.session_id}`",
        f"- **Target**: {result.target}",
        f"- **Model**: `{result.model}`",
        f"- **Timestamp**: {result.timestamp}",
        f"- **Duration**: {result.analysis_duration_seconds:.1f}s",
        f"- **Files analyzed**: {len(result.selected_files)}",
        "",
        "## Selected Files",
        "",
    ]
    for f in result.selected_files:
        lines.append(f"- `{f}`")
    lines += [
        "",
        "## Layer Distribution",
        "",
        "```",
        build_layer_stats(result.files_by_layer),
        "```",
        "",
        "## Project Structure",
        "",
        "```",
        result.project_structure,
        "```",
        "",
        "## Category Results",
        "",
    ]
    for cat in result.categories:
        status = "✅" if cat.error is None else f"❌ {cat.error}"
        rule_count = len(cat.rules)
        lines.append(f"- **{cat.category}**: {rule_count} rules {status}")
    return "\n".join(lines)


def render_category_md(cat: CategoryResult) -> str:
    lines = [
        f"# {cat.category.replace('_', ' ').title()} Analysis",
        "",
    ]
    if cat.error:
        lines += [f"> ⚠️ Analysis failed: {cat.error}", ""]
        if cat.raw_llm_output:
            lines += ["## Raw LLM Output", "", "```", cat.raw_llm_output[:2000], "```"]
        return "\n".join(lines)

    lines += [
        "## Design Intent",
        "",
        cat.design_intent,
        "",
        f"## Rules ({len(cat.rules)})",
        "",
    ]
    for rule in cat.rules:
        lines += _render_rule(rule)

    if cat.anti_patterns:
        lines += ["## Anti-Patterns", ""]
        for ap in cat.anti_patterns:
            lines += [
                f"### {ap.get('pattern', '?')}",
                "",
                f"**Why**: {ap.get('reason', '')}",
                "",
                f"**Alternative**: {ap.get('alternative', '')}",
                "",
            ]

    if cat.file_type_guides:
        lines += ["## File-Type Guides", ""]
        for ft, guide in cat.file_type_guides.items():
            lines += [f"### {ft}", "", guide, ""]

    if cat.checklist:
        lines += ["## Checklist", ""]
        for item in cat.checklist:
            lines.append(f"- [ ] {item}")
        lines.append("")

    return "\n".join(lines)


def render_layer_md(layer: str, categories: list[CategoryResult]) -> str:
    rules = [r for cat in categories for r in cat.rules if r.layer == layer]
    lines = [
        f"# {layer.title()} Layer Rules",
        "",
        f"> {_LAYER_CONTEXT.get(layer, '')}",
        "",
        f"**Total rules**: {len(rules)}",
        "",
    ]
    if not rules:
        lines += [f"*No rules tagged `{layer}` in this session.*", ""]
        return "\n".join(lines)

    by_category: dict[str, list[AnalysisRule]] = {}
    for cat in categories:
        for r in cat.rules:
            if r.layer == layer:
                by_category.setdefault(cat.category, []).append(r)

    for category, cat_rules in by_category.items():
        lines += [f"## {category.replace('_', ' ').title()}", ""]
        for rule in cat_rules:
            lines += _render_rule(rule)

    return "\n".join(lines)


def render_claude_md_entrypoint(result: SessionResult) -> str:
    must_rules = [
        r
        for cat in result.categories
        for r in cat.rules
        if r.priority == "MUST"
    ][:10]

    lines = [
        "# Code Style Rules",
        "",
        f"> Generated by code-hijack from `{result.target}`",
        f"> Session: `{result.session_id}` | Model: `{result.model}`",
        "",
        "## Layer Guide",
        "",
        "Load the relevant layer file based on what you're working on:",
        "",
    ]
    for layer, ctx in _LAYER_CONTEXT.items():
        fname = _LAYER_FILE_NAMES.get(layer, f"{layer}.md")
        lines.append(f"- **{layer}**: {ctx} ([{fname}]({fname}))")

    lines += [
        "",
        "## Top MUST Rules (All Layers)",
        "",
        f"*{len(must_rules)} most critical rules across all categories:*",
        "",
    ]
    for rule in must_rules:
        lines.append(f"- **[{rule.layer}/{rule.priority}]** {rule.rule}")

    return "\n".join(lines)


def render_system_prompt_md(result: SessionResult) -> str:
    must_rules = [r for cat in result.categories for r in cat.rules if r.priority == "MUST"]
    should_rules = [r for cat in result.categories for r in cat.rules if r.priority == "SHOULD"]

    lines = [
        "# System Prompt",
        "",
        f"You are a senior developer working on `{result.target}`.",
        "Follow these coding rules extracted from the codebase analysis.",
        "When writing code, treat MUST rules as non-negotiable constraints.",
        "",
        "## MUST Rules",
        "",
    ]
    for rule in must_rules:
        lines.append(f"- [{rule.layer}] {rule.rule}")

    if should_rules:
        lines += ["", "## SHOULD Rules", ""]
        for rule in should_rules:
            lines.append(f"- [{rule.layer}] {rule.rule}")

    lines += [
        "",
        "## Anti-Patterns to Avoid",
        "",
    ]
    for cat in result.categories:
        for ap in cat.anti_patterns:
            pattern = ap.get("pattern", "")
            if pattern:
                lines.append(f"- {pattern}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# File writing
# ---------------------------------------------------------------------------

def write_output(result: SessionResult, output_base: Path) -> None:
    """세션별 raw 파일 + integrated 통합 파일을 모두 작성한다."""
    session_dir = output_base / result.session_id
    session_dir.mkdir(parents=True, exist_ok=True)

    _write_session_files(result, session_dir)
    _write_integrated_files(result, output_base / "integrated")


def _write_session_files(result: SessionResult, session_dir: Path) -> None:
    (session_dir / "meta.md").write_text(render_meta_md(result), encoding="utf-8")
    (session_dir / "session.json").write_text(
        json.dumps(result.to_json(), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    for cat in result.categories:
        (session_dir / f"{cat.category}.md").write_text(
            render_category_md(cat), encoding="utf-8"
        )


def _write_integrated_files(result: SessionResult, integrated_dir: Path) -> None:
    integrated_dir.mkdir(parents=True, exist_ok=True)

    for layer in _LAYERS:
        fname = _LAYER_FILE_NAMES[layer]
        (integrated_dir / fname).write_text(
            render_layer_md(layer, result.categories), encoding="utf-8"
        )

    (integrated_dir / "CLAUDE.md").write_text(
        render_claude_md_entrypoint(result), encoding="utf-8"
    )
    (integrated_dir / "system-prompt.md").write_text(
        render_system_prompt_md(result), encoding="utf-8"
    )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _render_rule(rule: AnalysisRule) -> list[str]:
    lines = [
        f"### {rule.rule}",
        "",
        f"**Priority**: `{rule.priority}` | **Confidence**: `{rule.confidence}`"
        f" | **Layer**: `{rule.layer}`",
        "",
        f"**Why**: {rule.reason}",
        "",
    ]
    if rule.ref_files:
        lines += [f"**Reference**: {', '.join(f'`{f}`' for f in rule.ref_files)}", ""]
    if rule.good_example:
        lines += ["**✅ Good**:", "```", rule.good_example, "```", ""]
    if rule.bad_example:
        lines += ["**❌ Bad**:", "```", rule.bad_example, "```", ""]
    return lines
