# ruff: noqa: E501
# Long lines are intrinsic here: this file emits markdown bodies inline
# (same rationale as the LLM prompt template in critic.py).
"""HarnessAI integration adapter — convert a code-hijack SessionResult into
HarnessAI-shaped docs (conventions.md / guidelines/ / shared-lessons-candidates.md).

Design principles:
- Scope filter: only `cross_project` rules are auto-applied. `framework_internal`
  is excluded (internal framework decision, irrelevant downstream).
  `domain_specific` becomes a lesson candidate (re-evaluation needed).
- User review first: nothing is merged into HarnessAI's actual files
  (`shared-lessons.md` etc.). Output is candidate-only — humans decide what
  to register.
- Minimal duplication: distinct from generator.py (this module emits the
  HarnessAI shape — decision tables / per-area guides — not the agent-ready
  layer files).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from hijack.core.generator import render_evidence_chain
from hijack.core.models import AnalysisRule, SessionResult

# code-hijack layer -> HarnessAI guidelines/ subdirectory.
# None means: not under guidelines/ (folded into conventions.md instead).
_LAYER_TO_DIR: dict[str, str | None] = {
    "frontend": "frontend",
    "backend": "backend",
    "db": "backend",  # DB is the data sub-layer of backend (filename gets a db- prefix).
    "devops": "devops",
    "shared": None,  # shared rules are absorbed into conventions.md
}

# category -> guideline filename (with extension).
# `dependencies` is intentionally absent: it becomes a section inside
# conventions.md ("dependency policy"), not a standalone guide.
_CATEGORY_TO_FILENAME: dict[str, str] = {
    "architecture": "structure.md",
    "coding_style": "style.md",
    "api_design": "api.md",
    "data_model": "models.md",
    "state_management": "state.md",
    "security": "security.md",
    "testing": "testing.md",
    "performance": "performance.md",
    "devops": "ci.md",
}


@dataclass
class ExportSummary:
    """Result of a harness-export run. Used by both CLI output and tests."""

    output_dir: Path
    conventions_path: Path
    guideline_paths: list[Path] = field(default_factory=list)
    lesson_candidates_path: Path | None = None
    cross_project_count: int = 0
    framework_internal_count: int = 0
    domain_specific_count: int = 0
    anti_pattern_count: int = 0


# ---------------------------------------------------------------------------
# Public entry
# ---------------------------------------------------------------------------

def export_session(session: SessionResult, output_dir: Path) -> ExportSummary:
    """Convert SessionResult into HarnessAI-shaped docs and write to disk.

    Output files:
    - <output>/conventions.md
    - <output>/guidelines/<layer-dir>/<category>.md (per layer x category combo)
    - <output>/shared-lessons-candidates.md (anti-patterns + domain-specific rules)
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    summary = ExportSummary(
        output_dir=output_dir,
        conventions_path=output_dir / "conventions.md",
    )

    _count_scopes(session, summary)

    summary.conventions_path.write_text(
        _render_conventions(session), encoding="utf-8"
    )

    summary.guideline_paths = _write_guidelines(session, output_dir)

    lesson_md = _render_lesson_candidates(session, summary)
    if lesson_md:
        target = output_dir / "shared-lessons-candidates.md"
        target.write_text(lesson_md, encoding="utf-8")
        summary.lesson_candidates_path = target

    return summary


def _count_scopes(session: SessionResult, summary: ExportSummary) -> None:
    for cat in session.categories:
        for rule in cat.rules:
            scope = rule.scope or "cross_project"
            if scope == "cross_project":
                summary.cross_project_count += 1
            elif scope == "framework_internal":
                summary.framework_internal_count += 1
            elif scope == "domain_specific":
                summary.domain_specific_count += 1
        summary.anti_pattern_count += len(cat.anti_patterns)


# ---------------------------------------------------------------------------
# conventions.md
# ---------------------------------------------------------------------------

def _render_conventions(session: SessionResult) -> str:
    cross_rules = _filter_rules(session, scope="cross_project")
    shared_rules = [r for r in cross_rules if r.layer == "shared"]
    backend_rules = [r for r in cross_rules if r.layer in ("backend", "db")]
    frontend_rules = [r for r in cross_rules if r.layer == "frontend"]

    lines = [
        "# Project Conventions — extracted by code-hijack",
        "",
        f"> Generated by code-hijack from `{session.target}`",
        f"> Session: `{session.session_id}` | Model: `{session.model}`",
        "",
        "> Review this document, then apply it as your HarnessAI `docs/conventions.md`.",
        "> Rules with `framework_internal` scope are excluded — they describe the",
        "> source codebase's own internals and don't transfer to a new project.",
        "",
        "## Authority order (top wins on conflict)",
        "",
        "1. `docs/conventions.md` (this document) + `docs/guidelines/`",
        "2. Project root `CLAUDE.md`",
        "3. `agents/<role>/CLAUDE.md`",
        "4. `docs/skeleton.md`",
        "",
    ]

    if shared_rules:
        lines += ["## Core principles (all layers)", ""]
        lines += _render_decisions_table(shared_rules)
        lines += [""]

    if backend_rules:
        lines += ["## Backend decisions", ""]
        lines += _render_decisions_table(backend_rules)
        lines += [""]

    if frontend_rules:
        lines += ["## Frontend decisions", ""]
        lines += _render_decisions_table(frontend_rules)
        lines += [""]

    # Dependency policy — `dependencies` category folded in here.
    deps_section = _render_dependencies_section(session)
    if deps_section:
        lines += deps_section + [""]

    # Guideline index
    lines += ["## Guideline index", ""]
    by_layer_dir = _group_rules_for_index(session)
    if not by_layer_dir:
        lines += ["*No guideline files generated (no cross_project rules).*"]
    else:
        for (layer_dir, category), count in sorted(by_layer_dir.items()):
            filename = _CATEGORY_TO_FILENAME.get(category, f"{category}.md")
            if layer_dir == "backend" and _is_db_category(session, category):
                filename = f"db-{filename}"
            link = f"guidelines/{layer_dir}/{filename}"
            lines.append(f"- [{link}]({link}) — {category} ({count} rules)")

    # Scope distribution (informational)
    lines += [
        "",
        "## Scope distribution (info)",
        "",
        f"- cross_project: {sum(1 for r in cross_rules)} rules (in this doc + guidelines)",
        f"- framework_internal: {sum(1 for r in _filter_rules(session, 'framework_internal'))} rules (excluded)",
        f"- domain_specific: {sum(1 for r in _filter_rules(session, 'domain_specific'))} rules (see shared-lessons-candidates.md)",
    ]

    return "\n".join(lines)


def _render_decisions_table(rules: list[AnalysisRule]) -> list[str]:
    """Render a HarnessAI-style decision table."""
    lines = [
        "| Topic | Decision (summary) | Priority | Why | Reference |",
        "|---|---|---|---|---|",
    ]
    for rule in rules:
        topic = _topic_from_rule(rule.rule)
        decision = _truncate(rule.rule, 80)
        why = _truncate(rule.reason, 60)
        ref = rule.ref_files[0] if rule.ref_files else "-"
        lines.append(
            f"| {topic} | {decision} | {rule.priority} | {why} | `{ref}` |"
        )
    return lines


def _render_dependencies_section(session: SessionResult) -> list[str]:
    """Fold the `dependencies` category into a single conventions section."""
    deps_rules = [
        r
        for cat in session.categories
        if cat.category == "dependencies"
        for r in cat.rules
        if (r.scope or "cross_project") == "cross_project"
    ]
    if not deps_rules:
        return []
    lines = ["## Dependency policy", ""]
    for rule in deps_rules:
        lines.append(f"- **[{rule.priority}]** {rule.rule}")
        if rule.reason:
            lines.append(f"  - Why: {rule.reason}")
    return lines


# ---------------------------------------------------------------------------
# guidelines/
# ---------------------------------------------------------------------------

def _write_guidelines(session: SessionResult, output_dir: Path) -> list[Path]:
    """Emit one guidelines/<layer-dir>/<file>.md per layer x category combo."""
    written: list[Path] = []
    guidelines_root = output_dir / "guidelines"

    # Group rules by (layer_dir, filename).
    grouped: dict[tuple[str, str], list[AnalysisRule]] = {}
    for cat in session.categories:
        filename = _CATEGORY_TO_FILENAME.get(cat.category)
        if filename is None:
            continue  # unmapped category (e.g. dependencies) — skip
        for rule in cat.rules:
            if (rule.scope or "cross_project") != "cross_project":
                continue
            layer_dir = _LAYER_TO_DIR.get(rule.layer)
            if layer_dir is None:
                continue  # shared layer is absorbed into conventions.md
            target_filename = (
                f"db-{filename}" if rule.layer == "db" else filename
            )
            grouped.setdefault((layer_dir, target_filename), []).append(rule)

    for (layer_dir, filename), rules in sorted(grouped.items()):
        target = guidelines_root / layer_dir / filename
        target.parent.mkdir(parents=True, exist_ok=True)
        # Source category inferred from the first rule (grouping key is layer/file).
        category = next(
            (
                cat.category
                for cat in session.categories
                if any(r in cat.rules for r in rules)
            ),
            "",
        )
        body = _render_guideline(layer_dir, category, rules, session=session)
        target.write_text(body, encoding="utf-8")
        written.append(target)

    return written


def _render_guideline(
    layer_dir: str,
    category: str,
    rules: list[AnalysisRule],
    *,
    session: SessionResult | None = None,
) -> str:
    title_layer = layer_dir.title()
    title_category = category.replace("_", " ").title() if category else ""
    title = f"{title_layer} — {title_category}".rstrip(" —")
    lines = [
        f"# {title}",
        "",
        f"> Extracted by code-hijack. Cross-project scope only ({len(rules)} rules).",
        "",
    ]
    if session is not None:
        # Prepend the category's design_intent if present.
        for cat in session.categories:
            if cat.category == category and cat.design_intent:
                lines += ["## Design Intent", "", cat.design_intent, ""]
                break

    lines += ["## Rules", ""]
    for rule in rules:
        lines += _render_full_rule(rule)

    return "\n".join(lines)


def _render_full_rule(rule: AnalysisRule) -> list[str]:
    out = [
        f"### {rule.rule}",
        "",
        f"**Priority**: `{rule.priority}` | **Confidence**: `{rule.confidence}`"
        f" | **Layer**: `{rule.layer}`",
        "",
        f"**Why**: {rule.reason}",
        "",
    ]
    if rule.ref_files:
        out += [f"**Reference**: {', '.join(f'`{f}`' for f in rule.ref_files)}", ""]
    if rule.good_example:
        out += ["**✅ Good**:", "```", rule.good_example, "```", ""]
    if rule.bad_example:
        out += ["**❌ Bad**:", "```", rule.bad_example, "```", ""]
    if rule.evidence:
        # Mirror generator.py: the senior's verbatim rationale must propagate
        # through harness-export to HarnessAI guidelines too. Without this,
        # downstream consumers of HarnessAI docs see only the 1-line gist.
        out += render_evidence_chain(rule.evidence)
    return out


# ---------------------------------------------------------------------------
# shared-lessons-candidates.md
# ---------------------------------------------------------------------------

def _render_lesson_candidates(
    session: SessionResult, summary: ExportSummary
) -> str:
    domain_rules = _filter_rules(session, scope="domain_specific")
    has_anti_patterns = any(cat.anti_patterns for cat in session.categories)
    if not domain_rules and not has_anti_patterns:
        return ""

    lines = [
        "# LESSON candidates — extracted by code-hijack",
        "",
        f"> Generated by code-hijack from `{session.target}`",
        "",
        "> Candidates only — review and register manually as LESSON-NNN entries",
        "> in `backend/docs/shared-lessons.md`. Nothing here is auto-applied.",
        "",
    ]

    # Anti-patterns
    if has_anti_patterns:
        lines += ["## Anti-Patterns (auto-extracted)", ""]
        for cat in session.categories:
            for ap in cat.anti_patterns:
                pattern = ap.get("pattern", "")
                if not pattern:
                    continue
                lines += [
                    f"### [{cat.category}] {pattern}",
                    "",
                    f"**Why**: {ap.get('reason', '')}",
                    "",
                    f"**Alternative**: {ap.get('alternative', '')}",
                    "",
                ]

    # Domain-specific rules — re-evaluate before applying to a new domain.
    if domain_rules:
        lines += [
            "## Domain-Specific Rules (re-evaluation needed)",
            "",
            "> The rules below encode domain decisions of the analyzed project.",
            "> Apply to a different domain only after adjusting values / ranges /",
            "> names. Promote to LESSON entries once you've judged the fit.",
            "",
        ]
        for rule in domain_rules:
            lines += [
                f"### {rule.rule}",
                "",
                f"**Layer**: `{rule.layer}` | **Priority**: `{rule.priority}`",
                "",
                f"**Why**: {rule.reason}",
                "",
            ]
            if rule.ref_files:
                lines.append(
                    f"**Reference**: {', '.join(f'`{f}`' for f in rule.ref_files)}"
                )
                lines.append("")
            if rule.evidence:
                lines += render_evidence_chain(rule.evidence)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _filter_rules(session: SessionResult, scope: str) -> list[AnalysisRule]:
    return [
        rule
        for cat in session.categories
        for rule in cat.rules
        if (rule.scope or "cross_project") == scope
    ]


def _topic_from_rule(rule_text: str) -> str:
    """Compress a rule into a 4-6 word "topic" label for the decisions table."""
    words = rule_text.replace("`", "").split()
    if len(words) <= 4:
        return " ".join(words)
    return " ".join(words[:4]) + "…"


def _truncate(text: str, max_len: int) -> str:
    text = text.replace("\n", " ").strip()
    if len(text) <= max_len:
        return text
    return text[: max_len - 1] + "…"


def _is_db_category(session: SessionResult, category: str) -> bool:
    """True iff this category has at least one cross_project rule on the db layer."""
    for cat in session.categories:
        if cat.category != category:
            continue
        for rule in cat.rules:
            if rule.layer == "db" and (rule.scope or "cross_project") == "cross_project":
                return True
    return False


def _group_rules_for_index(
    session: SessionResult,
) -> dict[tuple[str, str], int]:
    """Index counter for the conventions guideline-index section."""
    out: dict[tuple[str, str], int] = {}
    for cat in session.categories:
        if cat.category not in _CATEGORY_TO_FILENAME:
            continue
        for rule in cat.rules:
            if (rule.scope or "cross_project") != "cross_project":
                continue
            layer_dir = _LAYER_TO_DIR.get(rule.layer)
            if layer_dir is None:
                continue
            key = (layer_dir, cat.category)
            out[key] = out.get(key, 0) + 1
    return out
