# ruff: noqa: E501
# 이 파일은 한국어 본문을 markdown 으로 출력하는 헬퍼라 긴 라인이 본질적
# (critic.py 의 LLM 프롬프트 템플릿과 같은 사유).
"""HarnessAI 통합용 변환기 — code-hijack 세션 산출물을 conventions.md / guidelines/ /
shared-lessons-candidates.md 형식으로 변환한다 (M2).

설계 원칙:
- scope 필터링 — cross_project 만 자동 적용. framework_internal 은 제외, domain_specific
  은 lesson 후보로.
- 사용자 검토 우선 — 어떤 항목도 HarnessAI 본문 (shared-lessons.md 등) 에 자동 머지하지
  않음. candidate 파일로 출력해서 사람이 검토 후 수동 적용.
- 본문 중복 최소화 — generator.py 와 별도 형식 (HarnessAI 의 결정 표 / 가이드 형식).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from hijack.core.models import AnalysisRule, SessionResult

# code-hijack layer → HarnessAI guidelines/ 디렉토리. None = guidelines 아래 X (conventions 로).
_LAYER_TO_DIR: dict[str, str | None] = {
    "frontend": "frontend",
    "backend": "backend",
    "db": "backend",  # DB 는 backend 의 데이터 레이어 — backend/db-*.md 로 표기
    "devops": "devops",
    "shared": None,  # shared 는 conventions.md 로 흡수
}

# category → guideline 파일명 (확장자 포함). dependencies 는 conventions 의 whitelist 섹션
# 으로만 들어가서 별도 파일 없음.
_CATEGORY_TO_FILENAME: dict[str, str] = {
    "architecture": "structure.md",
    "coding_style": "style.md",
    "api_design": "api.md",
    "data_model": "models.md",
    "state_management": "state.md",
    "security": "security.md",
    "testing": "testing.md",
    "performance": "performance.md",
    "devops": "ci.md",
}


@dataclass
class ExportSummary:
    """harness-export 결과 요약. CLI 출력 + 테스트 검증용."""

    output_dir: Path
    conventions_path: Path
    guideline_paths: list[Path] = field(default_factory=list)
    lesson_candidates_path: Path | None = None
    cross_project_count: int = 0
    framework_internal_count: int = 0
    domain_specific_count: int = 0
    anti_pattern_count: int = 0


# ---------------------------------------------------------------------------
# Public entry
# ---------------------------------------------------------------------------

def export_session(session: SessionResult, output_dir: Path) -> ExportSummary:
    """SessionResult 를 HarnessAI 형식으로 변환해 디스크에 작성.

    출력 파일:
    - <output>/conventions.md
    - <output>/guidelines/<layer-dir>/<category>.md (각 layer × category 조합)
    - <output>/shared-lessons-candidates.md (anti_patterns + domain_specific rules)
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    summary = ExportSummary(
        output_dir=output_dir,
        conventions_path=output_dir / "conventions.md",
    )

    _count_scopes(session, summary)

    summary.conventions_path.write_text(
        _render_conventions(session), encoding="utf-8"
    )

    summary.guideline_paths = _write_guidelines(session, output_dir)

    lesson_md = _render_lesson_candidates(session, summary)
    if lesson_md:
        target = output_dir / "shared-lessons-candidates.md"
        target.write_text(lesson_md, encoding="utf-8")
        summary.lesson_candidates_path = target

    return summary


def _count_scopes(session: SessionResult, summary: ExportSummary) -> None:
    for cat in session.categories:
        for rule in cat.rules:
            scope = rule.scope or "cross_project"
            if scope == "cross_project":
                summary.cross_project_count += 1
            elif scope == "framework_internal":
                summary.framework_internal_count += 1
            elif scope == "domain_specific":
                summary.domain_specific_count += 1
        summary.anti_pattern_count += len(cat.anti_patterns)


# ---------------------------------------------------------------------------
# conventions.md
# ---------------------------------------------------------------------------

def _render_conventions(session: SessionResult) -> str:
    cross_rules = _filter_rules(session, scope="cross_project")
    shared_rules = [r for r in cross_rules if r.layer == "shared"]
    backend_rules = [r for r in cross_rules if r.layer in ("backend", "db")]
    frontend_rules = [r for r in cross_rules if r.layer == "frontend"]

    lines = [
        "# 프로젝트 컨벤션 — code-hijack 추출본",
        "",
        f"> Generated by code-hijack from `{session.target}`",
        f"> Session: `{session.session_id}` | Model: `{session.model}`",
        "",
        "> 이 문서는 사용자 검토 후 HarnessAI 의 `docs/conventions.md` 로 적용한다.",
        "> `framework_internal` scope 의 규칙은 제외 — 추출된 프레임워크 내부 결정이라 새 프로젝트엔 무관.",
        "",
        "## 권위 순서 (충돌 시 위가 우선)",
        "",
        "1. `docs/conventions.md` (이 문서) + `docs/guidelines/`",
        "2. 프로젝트 루트 `CLAUDE.md`",
        "3. `agents/<role>/CLAUDE.md`",
        "4. `docs/skeleton.md`",
        "",
    ]

    if shared_rules:
        lines += ["## 핵심 원칙 (모든 레이어 공통)", ""]
        lines += _render_decisions_table(shared_rules)
        lines += [""]

    if backend_rules:
        lines += ["## Backend 결정", ""]
        lines += _render_decisions_table(backend_rules)
        lines += [""]

    if frontend_rules:
        lines += ["## Frontend 결정", ""]
        lines += _render_decisions_table(frontend_rules)
        lines += [""]

    # 허용 라이브러리 (dependencies 카테고리 → 본문 텍스트로)
    deps_section = _render_dependencies_section(session)
    if deps_section:
        lines += deps_section + [""]

    # 가이드 색인
    lines += ["## 가이드 색인", ""]
    by_layer_dir = _group_rules_for_index(session)
    if not by_layer_dir:
        lines += ["*가이드라인 파일 없음 (cross_project rule 부재).*"]
    else:
        for (layer_dir, category), count in sorted(by_layer_dir.items()):
            filename = _CATEGORY_TO_FILENAME.get(category, f"{category}.md")
            if layer_dir == "backend" and _is_db_category(session, category):
                filename = f"db-{filename}"
            link = f"guidelines/{layer_dir}/{filename}"
            lines.append(f"- [{link}]({link}) — {category} ({count} rules)")

    # Scope 분포
    lines += [
        "",
        "## Scope 분포 (참고)",
        "",
        f"- cross_project: {sum(1 for r in cross_rules)} rules (이 문서 + guidelines 에 반영)",
        f"- framework_internal: {sum(1 for r in _filter_rules(session, 'framework_internal'))} rules (출력 제외)",
        f"- domain_specific: {sum(1 for r in _filter_rules(session, 'domain_specific'))} rules (shared-lessons-candidates.md 참조)",
    ]

    return "\n".join(lines)


def _render_decisions_table(rules: list[AnalysisRule]) -> list[str]:
    """결정 표 형식 렌더링. HarnessAI conventions.md 스타일."""
    lines = [
        "| 주제 | 결정 (요약) | Priority | Why | Reference |",
        "|---|---|---|---|---|",
    ]
    for rule in rules:
        topic = _topic_from_rule(rule.rule)
        decision = _truncate(rule.rule, 80)
        why = _truncate(rule.reason, 60)
        ref = rule.ref_files[0] if rule.ref_files else "-"
        lines.append(
            f"| {topic} | {decision} | {rule.priority} | {why} | `{ref}` |"
        )
    return lines


def _render_dependencies_section(session: SessionResult) -> list[str]:
    """dependencies 카테고리의 rule 들을 conventions 의 한 섹션으로."""
    deps_rules = [
        r
        for cat in session.categories
        if cat.category == "dependencies"
        for r in cat.rules
        if (r.scope or "cross_project") == "cross_project"
    ]
    if not deps_rules:
        return []
    lines = ["## 의존성 정책 (dependencies)", ""]
    for rule in deps_rules:
        lines.append(f"- **[{rule.priority}]** {rule.rule}")
        if rule.reason:
            lines.append(f"  - Why: {rule.reason}")
    return lines


# ---------------------------------------------------------------------------
# guidelines/
# ---------------------------------------------------------------------------

def _write_guidelines(session: SessionResult, output_dir: Path) -> list[Path]:
    """layer × category 조합마다 guidelines/<layer-dir>/<file>.md 생성."""
    written: list[Path] = []
    guidelines_root = output_dir / "guidelines"

    # 그룹: (layer_dir, filename) → rules
    grouped: dict[tuple[str, str], list[AnalysisRule]] = {}
    for cat in session.categories:
        filename = _CATEGORY_TO_FILENAME.get(cat.category)
        if filename is None:
            continue  # 미매핑 카테고리 (e.g. dependencies) 는 건너뜀
        for rule in cat.rules:
            if (rule.scope or "cross_project") != "cross_project":
                continue
            layer_dir = _LAYER_TO_DIR.get(rule.layer)
            if layer_dir is None:
                continue  # shared 는 conventions 로 흡수
            target_filename = (
                f"db-{filename}" if rule.layer == "db" else filename
            )
            grouped.setdefault((layer_dir, target_filename), []).append(rule)

    for (layer_dir, filename), rules in sorted(grouped.items()):
        target = guidelines_root / layer_dir / filename
        target.parent.mkdir(parents=True, exist_ok=True)
        # category 는 첫 rule 의 source category 로 추론 — grouping 키와 무관
        category = next(
            (
                cat.category
                for cat in session.categories
                if any(r in cat.rules for r in rules)
            ),
            "",
        )
        body = _render_guideline(layer_dir, category, rules, session=session)
        target.write_text(body, encoding="utf-8")
        written.append(target)

    return written


def _render_guideline(
    layer_dir: str,
    category: str,
    rules: list[AnalysisRule],
    *,
    session: SessionResult | None = None,
) -> str:
    title_layer = layer_dir.title()
    title_category = category.replace("_", " ").title() if category else ""
    title = f"{title_layer} — {title_category}".rstrip(" —")
    lines = [
        f"# {title}",
        "",
        f"> code-hijack 추출. cross_project scope 만 포함 ({len(rules)} rules).",
        "",
    ]
    if session is not None:
        # 카테고리의 design_intent 가 있으면 첨부
        for cat in session.categories:
            if cat.category == category and cat.design_intent:
                lines += ["## Design Intent", "", cat.design_intent, ""]
                break

    lines += ["## Rules", ""]
    for rule in rules:
        lines += _render_full_rule(rule)

    return "\n".join(lines)


def _render_full_rule(rule: AnalysisRule) -> list[str]:
    out = [
        f"### {rule.rule}",
        "",
        f"**Priority**: `{rule.priority}` | **Confidence**: `{rule.confidence}`"
        f" | **Layer**: `{rule.layer}`",
        "",
        f"**Why**: {rule.reason}",
        "",
    ]
    if rule.ref_files:
        out += [f"**Reference**: {', '.join(f'`{f}`' for f in rule.ref_files)}", ""]
    if rule.good_example:
        out += ["**✅ Good**:", "```", rule.good_example, "```", ""]
    if rule.bad_example:
        out += ["**❌ Bad**:", "```", rule.bad_example, "```", ""]
    return out


# ---------------------------------------------------------------------------
# shared-lessons-candidates.md
# ---------------------------------------------------------------------------

def _render_lesson_candidates(
    session: SessionResult, summary: ExportSummary
) -> str:
    domain_rules = _filter_rules(session, scope="domain_specific")
    has_anti_patterns = any(cat.anti_patterns for cat in session.categories)
    if not domain_rules and not has_anti_patterns:
        return ""

    lines = [
        "# LESSON 후보 — code-hijack 추출",
        "",
        f"> Generated by code-hijack from `{session.target}`",
        "",
        "> 이 문서는 LESSON 후보 모음. 사용자가 검토 후 `backend/docs/shared-lessons.md`",
        "> 의 LESSON-NNN 으로 등록 — 자동 등록 X.",
        "",
    ]

    # Anti-patterns
    if has_anti_patterns:
        lines += ["## Anti-Patterns (자동 추출)", ""]
        for cat in session.categories:
            for ap in cat.anti_patterns:
                pattern = ap.get("pattern", "")
                if not pattern:
                    continue
                lines += [
                    f"### [{cat.category}] {pattern}",
                    "",
                    f"**Why**: {ap.get('reason', '')}",
                    "",
                    f"**Alternative**: {ap.get('alternative', '')}",
                    "",
                ]

    # Domain-specific rules — 새 도메인에선 재평가 필요
    if domain_rules:
        lines += [
            "## Domain-Specific Rules (재평가 필요)",
            "",
            "> 아래 규칙들은 추출된 프로젝트의 도메인 결정을 반영. 다른 도메인에",
            "> 적용 시 값/범위/이름 변경이 필요할 수 있음. 사용자가 적합성 판단 후 LESSON 으로 등록.",
            "",
        ]
        for rule in domain_rules:
            lines += [
                f"### {rule.rule}",
                "",
                f"**Layer**: `{rule.layer}` | **Priority**: `{rule.priority}`",
                "",
                f"**Why**: {rule.reason}",
                "",
            ]
            if rule.ref_files:
                lines.append(
                    f"**Reference**: {', '.join(f'`{f}`' for f in rule.ref_files)}"
                )
                lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _filter_rules(session: SessionResult, scope: str) -> list[AnalysisRule]:
    return [
        rule
        for cat in session.categories
        for rule in cat.rules
        if (rule.scope or "cross_project") == scope
    ]


def _topic_from_rule(rule_text: str) -> str:
    """결정 표의 '주제' 컬럼 — rule 의 첫 의미 단어 4-6 단어로 압축."""
    words = rule_text.replace("`", "").split()
    if len(words) <= 4:
        return " ".join(words)
    # 첫 4 단어 + ... (간결)
    return " ".join(words[:4]) + "…"


def _truncate(text: str, max_len: int) -> str:
    text = text.replace("\n", " ").strip()
    if len(text) <= max_len:
        return text
    return text[: max_len - 1] + "…"


def _is_db_category(session: SessionResult, category: str) -> bool:
    """해당 category 의 cross_project rule 이 db layer 에 하나라도 있는지."""
    for cat in session.categories:
        if cat.category != category:
            continue
        for rule in cat.rules:
            if rule.layer == "db" and (rule.scope or "cross_project") == "cross_project":
                return True
    return False


def _group_rules_for_index(
    session: SessionResult,
) -> dict[tuple[str, str], int]:
    """가이드 색인용 (layer_dir, category) → count 카운터."""
    out: dict[tuple[str, str], int] = {}
    for cat in session.categories:
        if cat.category not in _CATEGORY_TO_FILENAME:
            continue
        for rule in cat.rules:
            if (rule.scope or "cross_project") != "cross_project":
                continue
            layer_dir = _LAYER_TO_DIR.get(rule.layer)
            if layer_dir is None:
                continue
            key = (layer_dir, cat.category)
            out[key] = out.get(key, 0) + 1
    return out
